name: iOS CI with CocoaPods

on: workflow_dispatch

jobs:
  iOS:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
    - uses: actions/checkout@v2
    - name: Pod register
      run: pod trunk register liamxujia@outlook.com 'liamxujia' --description='GitHub register to trunk.'
    - name: Pod trunk
      run: pod trunk push react-expo.podspec --allow-warnings --verbose
